### ISSUE TITLE
Enhancement: Add Bitbucket social

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#13]
## What

Similar to: https://github.com/lepture/shibuya/blob/79547925539978614f8b925374126ce421952793/docs/customisation/social.rst#github

Basically, it would be nice to have this as an icon and option in `html_theme_options`

**Comment by JacobCoffee** [comment]
As an aside maybe it would be neat to have custom icons (either pointed to a path on disk or URL?)

**Comment by lepture** [comment]
Added `bitbucket_url`
