### ISSUE TITLE
Bug: `source_type`s defined with `bitbucket` do not render

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#14]
```py
html_context = {
    "source_type": "github", # swap to bitbucket, see that it doesnt render
    "source_user": "somerepo",
    "source_repo": "helloworld",
}
```
With `github`: 
<img width="271" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/7b10ae84-7466-4fa3-8515-8b82c59e5369">
With `bitbucket`: 
<img width="232" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/5eac7e1f-796f-4e05-83b8-2f950b5f4faf">

Also, I'm imagining that `bitbucket` will point to bitbucket.org:
https://github.com/lepture/shibuya/blob/79547925539978614f8b925374126ce421952793/src/shibuya/context.py#L83
 but is it possible to also specify in the cases of internally hosted Bitbucket instances? `bitbucket.company.com`

**Comment by JacobCoffee** [comment]
Testing Gitlab to help others, it renders
<img width="272" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/e178cd34-4bfc-4df2-b2a9-079b6fb487de">

**Comment by lepture** [comment]
@JacobCoffee It is because I can't find the bitbucket API of stars and forks count for bitbucket.
