### ISSUE TITLE
MAINT: Loosen up dependencies?

### ISSUE THREAD

**Issue by scott-huberty** [lepture/shibuya#17]
I noticed that this project's dependencies pin to specific versions of several packages:

https://github.com/lepture/shibuya/blob/49959762a15b7a9caaf3bdb6a770c3517260cdd9/requirements.txt#L1-L9

I understand that this might be to ensure reliability, but since there are a lot of users now (awesome!), in principle I think this can be loosened up in order to avoid dependency hell and technical debt. 

Based off other project's I've worked on, and a look at what other themes like [pydata_sphinx_theme](https://github.com/pydata/pydata-sphinx-theme) and [furo](https://github.com/pradyunsg/furo/blob/main/pyproject.toml) require, at a bare minimum I think shibuya can support  sphinx 6 and up (or even 5) and I think that should be okay. 

All of the other listed dependencies are not strictly requirements of `shibuya`, they are weak dependencies that users can install if they _want_ to use these extensions in their own documentation. The shibuya documentation already provides [really great instructions](https://shibuya.lepture.com/extensions/jupyter-sphinx/#jupyter-sphinx) for these extensions, so I don't think it's a problem to drop them. This is especially true of `ipykernel` which isn't even sphinx specific, and would only be needed if someone was using `jupyter-sphinx` in their documentation. If we dropped those dependencies, requirements.txt could just be 

```
sphinx>=6
Babel
```

I can submit a PR if it's welcome.

**Comment by scott-huberty** [comment]
... _Unless_ `requirement.txt` is only used by `readthedocs`... whereas `pip` uses `pyproject.toml` which only lists `sphinx` as a dependency 😆  

Maybe this can be changed to `requirements_doc.txt` to make sure this is very clear? At least that is what we do in [MNE-Python](https://github.com/mne-tools/mne-python)

You can close this issue.

**Comment by lepture** [comment]
@scott-huberty the `requirements.txt` is only used for shibuya documentation building. `pip` will use `pyproject.toml`.
