### ISSUE TITLE
Flashing screen when site is in dark mode

### ISSUE THREAD

**Issue by Tobi-De** [lepture/shibuya#2]
Hello there, I want to commend you for creating such a beautiful theme. I recently visited your website at https://shibuya.lepture.com/, and since my browser preference is set to dark mode, the dark theme was automatically applied. However, I noticed that every time I visit a new page, the site flashes from white to dark.

I'm using Firefox 110 on Linux, and I'm not sure if this issue is specific to my setup. Unfortunately, it's pretty difficult to capture in a screenshot, so I don't have anything to show you.

**Comment by lepture** [comment]
Oh. Thanks for your feedback. I believe I can reproduce it.

**Comment by Tobi-De** [comment]
Good job @lepture, it's fixed.
