### ISSUE TITLE
Theme-dependent media with caption

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#23]
Hello,

First, I love that theme, thanks a lot for the work 💪🏻 

Then, following https://shibuya.lepture.com/writing/media/#light-and-dark, I can't make it working when captions are in the loop. I am using markdown, and here is the code so far:

````md
```{figure} https://source.unsplash.com/daily?dog
   :width: 800
   :class: light-only
   :align: center

   A dog.

{figure} https://source.unsplash.com/daily?cat
   :width: 800
   :class: dark-only
   :align: center

    A cat.
```
````

And even with 2 distincts block codes like that, it will show both captions:

````md
```{figure} https://source.unsplash.com/daily?dog
   :width: 800
   :class: light-only
   :align: center

   A dog.
```

```{figure} https://source.unsplash.com/daily?cat
   :width: 800
   :class: dark-only
   :align: center

    A cat.
```
````

Do you see something wrog with that code? (I had to escape triple quotes in those examples, but that's just for GitHub).

**Comment by BoboTiG** [comment]
I just checked the generated HTML code, and the `xxx-only` class is not added to the whole `figure` but only to the first child element:

![Screenshot from 2024-01-30 09-57-30](https://github.com/lepture/shibuya/assets/2033598/f91cbb7d-5e42-4c44-8628-9b9565aa9afb)

**Comment by lepture** [comment]
How about using `figclass` instead of `class`?
