### ISSUE TITLE
Hidden code block caption background-color not properly set on light theme

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#26]
What a title 😅 

Here is some code to reproduce:

```rst
Test
====

.. admonition:: Benchmark
    :class: dropdown

    .. code-block:: python
        :caption: bench.py
    
        print("Hello, world!")
```

It will render like this in dark theme:
![preview-dark](https://github.com/lepture/shibuya/assets/2033598/b89218c5-e7a4-49e5-b761-2d9d17a3cd5e)

In light theme:
![preview-light](https://github.com/lepture/shibuya/assets/2033598/edac59a1-49a2-45fe-8e14-dfd970e5320d)

As you can see, with the light theme: the caption background color is not set.

**Comment by lepture** [comment]
fixed by https://github.com/lepture/shibuya/commit/cd0cade45a9504dedff52a970078f28a59c5956d

**Comment by BoboTiG** [comment]
Awesome, thank you very well for the quick response+fix.

**Comment by BoboTiG** [comment]
Out of curiosity, do you have anm ETA for the next release?

**Comment by lepture** [comment]
@BoboTiG released

**Comment by BoboTiG** [comment]
Yes, thank you. It's already in prod and works like a charm 👌🏻
