### ISSUE TITLE
Navigation bar (left side) does not keep current state

### ISSUE THREAD

**Issue by andrey-jef** [lepture/shibuya#27]
Hi,

The nav bar always return to top, instead of depending on where the currently viewed page.

Step to reproduce:
- On desktop web browser, visit: <https://shibuya.lepture.com/install/>
- Scroll the nav bar to bottom, and select item like `numpydoc`
- Then we see that the nav bar will return to top, instead of staying at the position of `numpydoc`

Alternative theme like Furo does not have this issue.

Thanks for your time with the theme development.

**Comment by lepture** [comment]
Furo behaves the same according to my test. If you want to collapse the left sidebar, you can use `globaltoc_expand_depth ` via https://shibuya.lepture.com/customisation/sidebar/

**Comment by lepture** [comment]
This may fixed the issue: https://github.com/lepture/shibuya/commit/202f96e19ccac03265a45140fa2571d88587975f

**Comment by andrey-jef** [comment]
> This may fixed the issue: [202f96e](https://github.com/lepture/shibuya/commit/202f96e19ccac03265a45140fa2571d88587975f)

Yes. I visit the docs page again. And the items on left side nav bar already stop at the correct position, instead of rebounding to top as previous.

https://shibuya.lepture.com/install/
