### ISSUE TITLE
Enhancement: Style tables similarly as codeblocks

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#35]
You're code block styling is really great, but I wish tables looked as good (without needing custom css or something)

<img width="948" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/c7a2494c-aae0-4e9b-af2e-838d209c8240">

Raw edges on tables:
<img width="964" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/905eb6ee-1d93-49d7-a4a9-4e2fae3ad840">

This is done using any of the available tables documented in https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html or just 
```rst
+----+----+
| 2  |  1 |
+----+----+
```

**Comment by lepture** [comment]
I don't understand the question. What should be improved? Can you give me an example?

**Comment by JacobCoffee** [comment]
The table has square edges and the code blocks / other elements are rounded :D It'd be cool if they matched the rest of the theme.

<img width="36" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/357ae732-dd98-4ec8-8979-0a5fc7120698">

**Comment by lepture** [comment]
Updated style for tables: https://shibuya.lepture.com/writing/table/

Please review the style, if it is ok, I'll make a new release.

**Comment by JacobCoffee** [comment]
Oh man that's perfect!

**Comment by lepture** [comment]
2024.4.8 released
