### ISSUE TITLE
Enhancement request: offset for navbar

### ISSUE THREAD

**Issue by tzing** [lepture/shibuya#4]
When using internal links like `:ref:` or `:py:class:`, the title shows at the top of the page and got shaded by the navbar.

For example, [Theme options](https://shibuya.lepture.com/customisation/#theme-options) looks like:

![Screenshot 2023-04-24 at 4 33 08 PM](https://user-images.githubusercontent.com/10195590/233942917-db3f7bad-3a98-4977-8051-fac0c26ee198.png)

It could be best to have an offset then we could see the title like:

![Screenshot 2023-04-24 at 4 34 54 PM](https://user-images.githubusercontent.com/10195590/233943237-b7749b75-ed3c-407d-84dd-768444a936f7.png)

**Comment by lepture** [comment]
fixed in master.
