### ISSUE TITLE
Sphinx 7.3 warning

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#41]
Hello,

Since Sphinx 7.3 I've this warning when building a website:

```
WARNING: cannot cache unpickable configuration value: 'html_context' (because it contains a function, class, or module object)
```

Here is my code: https://github.com/BoboTiG/luma/blob/f252f99f6035c884b3b1b52697585887840c5429/sources/conf.py#L70-L76

And the PR highlighting the problem: BoboTiG/luma#34
You can see exactly the issue in that job: https://github.com/BoboTiG/luma/actions/runs/8859830618/job/24330009352?pr=34#step:6:77

**Comment by lepture** [comment]
@BoboTiG fix in master code.

**Comment by BoboTiG** [comment]
Great, thank you :)
