### ISSUE TITLE
Rubric size

### ISSUE THREAD

**Issue by azmeuk** [lepture/shibuya#45]
I automatically generate some documentation for a `click` command with [sphinx-cli](https://sphinx-click.readthedocs.io). This makes a `h1` for a level 1 command, a `h2` for a sub-command, a `h3` for a sub-sub-command and so on. For command options and arguments, it generates a `<p class="rubric">` section containing the details.

### commands.rst
```rst
.. click:: commands:lvl1cli
   :prog: lvl1cli
   :nested: full
```

### commands.py
```python
import click


@click.group()
def lvl1cli():
    """1st level command"""


@lvl1cli.group()
def lvl2cli():
    """2nd level command"""


@lvl2cli.group()
def lvl3cli():
    """3rd level command"""


@lvl3cli.command()
@click.argument('some-argument')
@click.option('--option', default=1, help='Some option')
def sub4cli():
    """4th level command"""
```

With shibuya the `<p class="rubric">` section is bigger than the `h4`. For complex pages with a lot of commands, this become quite confusing.

Here is a simplified example, where `Options` and `Argument` are larger than `sub4cli`:
![Screenshot 2024-05-12 at 17-25-01 lvl1cli](https://github.com/lepture/shibuya/assets/60163/9643e482-cf0d-4ab9-973d-7f5e85268733)

I would have expected the `<p class="rubric">` section to be smaller than the related `hX` title in any situation.

What do you think?

**Comment by lepture** [comment]
https://github.com/lepture/shibuya/commit/22bb89c7503a0802062721c0fa122f2e6d57846d
