### ISSUE TITLE
Theme reverts to default when page is reopened

### ISSUE THREAD

**Issue by Alc-Alc** [lepture/shibuya#46]
Not sure if it's a feature request or issue or a config issue

Steps

1. Visit https://shibuya.lepture.com/
2. Change the theme to something that is not default (eg: if you are on light mode, change to dark mode and vice-versa)
3. Close the page
4. Reopen the page and notice that the theme is reverted (not the one you selected)

Thanks

**Comment by Alc-Alc** [comment]
Not sure if this is a conscious decision you made but I think the following should be stored in `localStorage` not `sessionStorage`?

https://github.com/lepture/shibuya/blob/c4e869220964de5bef857d26fd41d39783d6d066/static/js/theme.js#L12

**Comment by lepture** [comment]
Fixed in master code.
