### ISSUE TITLE
Floating images

### ISSUE THREAD

**Issue by azmeuk** [lepture/shibuya#47]
I would like to write a document where I list the different features of a project. This would consist in different sections with some text detailing the features, and at least one screenshot per feature.

To save some space, it would be nice if I could make the screenshots float on the right side of the text.

What do you think?

**Comment by lepture** [comment]
@azmeuk can you add a test case in https://shibuya.lepture.com/writing/media/

**Comment by lepture** [comment]
@azmeuk here is image with aligns: https://shibuya.lepture.com/writing/media/#align-image

Here is sidebar: https://shibuya.lepture.com/writing/markup/#sidebar

**Comment by azmeuk** [comment]
Thank you so much :pray:

**Comment by lepture** [comment]
Fixed

**Comment by azmeuk** [comment]
:ok_hand:
