### ISSUE TITLE
Align `viewcode` links on the right

### ISSUE THREAD

**Issue by azmeuk** [lepture/shibuya#48]
The [sphinx viewcode extension](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) adds *[source]* links near python object signatures.

![Screenshot 2024-05-22 at 10-19-16 Data models](https://github.com/lepture/shibuya/assets/60163/30c3acef-ce51-4e10-95af-4a321ce3faf5)

The link is displayed under the signature, but I think this would be nicer if it were aligned on the right side like it does in alabaster:

![Screenshot 2024-05-22 at 10-21-07 Data models — canaille documentation](https://github.com/lepture/shibuya/assets/60163/e502d219-2319-45f6-8fc0-cbb58e9f24b8)

What do you think?

**Comment by lepture** [comment]
The reason I put `[source]` in a new line is that sometime, the `class` name may be too long, and then it will mess up with the `[source]` link.
