### ISSUE TITLE
Use local fonts instead of hosting from google fonts?

### ISSUE THREAD

**Issue by baseplate-admin** [lepture/shibuya#55]
Hi,

I saw that the project uses google fonts,

There are many controversies around google font and i think it's better to provide the fonts in a static bundle.

Some resources:

- [Article on Court order](https://insights.project-a.com/the-court-says-dont-use-google-fonts/)
- https://github.com/google/fonts/issues/1495
- https://github.com/google/fonts/issues/1307

**Comment by lepture** [comment]
You can customize the fonts used by the theme https://shibuya.lepture.com/customisation/fonts/

If you don’t want to use google fonts, you can customize the web fonts template.
