### ISSUE TITLE
Nested toggles and code blocks

### ISSUE THREAD

**Issue by azmeuk** [lepture/shibuya#56]
The following code renders an un-necessary yellow border when closed:

```rst
.. tip::

   Sub-Attribute models are automatically created and set as members of their parent model classes.
   For instance the RFC7643 Group members sub-attribute can be accessed with ``Group.Members``.

    .. toggle::

        .. literalinclude :: ../samples/rfc7643-8.7.1-schema-group.json
           :language: json
           :caption: schema-group.json
```

![Screenshot 2024-06-20 at 12-38-21 Tutorial - scim2-models documentation](https://github.com/lepture/shibuya/assets/60163/165ee578-53ff-4dd8-9188-ce392af1935b)

When opened, the block is displayed like this:

![Screenshot 2024-06-20 at 12-39-01 Tutorial - scim2-models documentation](https://github.com/lepture/shibuya/assets/60163/3cd8c7bf-4bd6-4906-837a-9b3f60b07d36)

There is no such border if the toggle+litteralinclude blocks are outside an admonition.

**Comment by lepture** [comment]
This is caused by indentation.

You `tip` content is indented with 3 spaces, but `.. toggle` is indented with 4 spaces. Then RST generate the toggle in a `<blockquote>`.

**Comment by azmeuk** [comment]
Damn. Thank you.
Sorry for the noise :neutral_face:
