### ISSUE TITLE
[feature request]: Adding slack option in navbar

### ISSUE THREAD

**Issue by pateash** [lepture/shibuya#58]
we have options for reddit, discord etc
it will be great if we can have a option for **slack**

<img width="378" alt="image" src="https://github.com/lepture/shibuya/assets/16856802/51992259-bb72-4325-94a5-84fe421775bf">

or if we can support a partial similar to **foot-socials**

**Comment by lepture** [comment]
Feature added in master.

**Comment by lepture** [comment]
Released.

https://shibuya.lepture.com/customisation/social/#slack
https://shibuya.lepture.com/customisation/social/#custom-networks
