### ISSUE TITLE
Toggle-admonition containing a grid ends with too much padding/margin at the bottom

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#59]
Using the current latest version: `2024.7.13`.

Reproduction code:

    `````{admonition} Test
    :class: toggle

    Sentence 1.<br>
    Sentence 2:

    ````{grid} 2
    ```{grid-item}
    A<br>
    B<br>
    C
    ```

    ```{grid-item}
    D<br>
    E<br>
    F
    ```
    ````
    `````

## Previews

Normally, there is no "body" when the admonition is not toggled, but here there is:
![Screenshot 2024-08-18 at 20-05-54 La Nation Bison s’avance… - Base de connaissances du luma](https://github.com/user-attachments/assets/21a592c7-372f-4898-a399-b68ec526aa82)

And here, see the empty space at the bottom, it's too much:
![Screenshot 2024-08-18 at 20-05-41 La Nation Bison s’avance… - Base de connaissances du luma](https://github.com/user-attachments/assets/e62c3295-5b47-403a-af25-c6bfd8ba3284)

**Comment by lepture** [comment]
This is due to this grid has a `padding-bottom: 1.5rem !important`.

**Comment by lepture** [comment]
Fixed.

**Comment by lepture** [comment]
@BoboTiG fixed in latest release.
