### ISSUE TITLE
Feature: the audio tag

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#60]
Would it be an idea to add support for audio tags?

Something that would render to:

```html
<figure>
    <figcaption>CAPTION</figcaption>
    <audio controls preload="none" src="FILE"></audio>
</figure>
```

**Comment by BoboTiG** [comment]
:thinking: I used raw HTML at the end.

**Comment by lepture** [comment]
Added the `raw` example:

https://shibuya.lepture.com/writing/media/#audio
