### ISSUE TITLE
Too much space around lists in admonition

### ISSUE THREAD

**Issue by BoboTiG** [lepture/shibuya#61]
Reproduction code:

    Outside of admonition:
    - item
    - item

    ```{tip}
    Inside of admonition:
    - item
    - item
    ```

Preview:
![Screenshot 2024-08-21 at 15-40-56 La Nation Bison s’avance… - Base de connaissances du luma](https://github.com/user-attachments/assets/fb7fbdb1-38a3-40f3-ba4d-81ba2099ea8e)

There is more space inside the admonition, a little too much I think. Is it expected?

**Comment by lepture** [comment]
Fixed in [2024.8.26](https://github.com/lepture/shibuya/commit/cc14e8425c24145684b64f2d2dd211b60f8a94f7)
