### ISSUE TITLE
dark theme + jupyter colors

### ISSUE THREAD

**Issue by cboettig** [lepture/shibuya#66]
Thanks for sharing this fantastic theme, it looks great and is easy to work with.

One thing I've noticed is when using the Juypter integration, code-blocks look great in light mode but become nearly impossible to read in dark mode, e.g. taking a screen shot from your [docs in dark mode](https://shibuya.lepture.com/extensions/jupyter-sphinx/)

![image](https://github.com/user-attachments/assets/07de954c-d1ef-418d-96af-65cfdbe8dcab)

The cell background uses a high-contrast white, while the cell text is very washed out.  I think this would look better and be more readable if the cell background used a dark background (similar to say, Jupyter's own dark mode).  Is it possible to configure this?  (Apologies this is probably a simple css override)

**Comment by lepture** [comment]
Oh, thanks for the feedback. This could be caused by jupter's update. It works fine before.

**Comment by lepture** [comment]
2024.10.14 is released. This issue has been fixed.
