### ISSUE TITLE
Nested TOC Trees

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#7]
I seem to be hitting an issue with nested TOC trees.

Consider a setup like:

```rst
# docs/index.rst

.. toctree::
    :titlesonly:
    :caption: App Docs
    :hidden:

    api/index
```
```rst
# docs/api/index.rst

.. toctree::
    :titlesonly:
    :caption: Command API Docs
    :hidden:

    commands/index
```

Instead of indenting the next tree level it is flush, all links are on level 2, and there is still a caret indicating it should be an expandable list.

![image](https://github.com/lepture/shibuya/assets/45884264/0def916d-0c6d-48e6-9f48-4a8ce23d5ef3)

**Comment by lepture** [comment]
@JacobCoffee Can you provide the repository for me to debug?

**Comment by lepture** [comment]
@JacobCoffee This should be fixed.
