### ISSUE TITLE
Enhancement: Global TOC Settings

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#9]
Add settings for

- All table of contents to be expanded by default
- (and/or) Table of contents to be expanded to a certain level

References: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/page-toc.html
```py
html_theme_options = {
  "show_toc_level": 2
}
```

### Discussed in https://github.com/lepture/shibuya/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **JacobCoffee** July 22, 2023</sup>
I saw a changelog entry for global TOC menus.

I am wondering if I can customize having all (or certain) TOC trees expanded by default... or possible up to a certain level in the tree be expanded</div>

**Comment by lepture** [comment]
@JacobCoffee I've added a theme configuration: `globaltoc_expand_depth`

http://127.0.0.1:5500/customisation/sidebar/#global-toc
